#!/bin/bash
mkdir /data2/suguru/temp/Euphyes_vestris
mkdir /data2/suguru/temp/Cecropterus_dobra
mkdir /data2/suguru/temp/Megathymus_yuccae
mkdir /data2/suguru/temp/Callophrys_sheridanii
mkdir /data2/suguru/temp/Hesperopsis_libya
mkdir /data2/suguru/temp/Chlosyne_gorgone
mkdir /data2/suguru/temp/Satyrium_calanus
mkdir /data2/suguru/temp/Callophrys_augustinus
mkdir /data2/suguru/temp/Hesperia_leonardus
mkdir /data2/suguru/temp/Speyeria_egleis
mkdir /data2/suguru/temp/Lycaena_arota
mkdir /data2/suguru/temp/Chlorostrymon_simaethis
mkdir /data2/suguru/temp/Systasea_zampa
mkdir /data2/suguru/temp/Callophrys_spinetorum
mkdir /data2/suguru/temp/Celastrina_echo
mkdir /data2/suguru/temp/Speyeria_callippe
mkdir /data2/suguru/temp/Vanessa_virginiensis
mkdir /data2/suguru/temp/Polygonia_interrogationis
mkdir /data2/suguru/temp/Erynnis_brizo
mkdir /data2/suguru/temp/Satyrium_californica
mkdir /data2/suguru/temp/Lycaena_cupreus
mkdir /data2/suguru/temp/Agriades_glandon
mkdir /data2/suguru/temp/Satyrium_titus
mkdir /data2/suguru/temp/Plebejus_idas
mkdir /data2/suguru/temp/Hesperia_pahaska
mkdir /data2/suguru/temp/Pyrgus_scriptura
mkdir /data2/suguru/temp/Erynnis_propertius
mkdir /data2/suguru/temp/Pyrisitia_lisa
mkdir /data2/suguru/temp/Hesperia_colorado
mkdir /data2/suguru/temp/Speyeria_aphrodite
mkdir /data2/suguru/temp/Euphilotes_enoptes
mkdir /data2/suguru/temp/Polygonia_faunus
mkdir /data2/suguru/temp/Atlides_halesus
mkdir /data2/suguru/temp/Boloria_chariclea
mkdir /data2/suguru/temp/Danaus_plexippus
mkdir /data2/suguru/temp/Tharsalea_editha
mkdir /data2/suguru/temp/Polygonia_gracilis
mkdir /data2/suguru/temp/Erynnis_horatius
mkdir /data2/suguru/temp/Icaricia_saepiolus
mkdir /data2/suguru/temp/Zerene_cesonia
mkdir /data2/suguru/temp/Lerodea_eufala
mkdir /data2/suguru/temp/Heliopetes_ericetorum
mkdir /data2/suguru/temp/Erebia_magdalena
mkdir /data2/suguru/temp/Pholisora_catullus
mkdir /data2/suguru/temp/Icaricia_icarioides
mkdir /data2/suguru/temp/Poladryas_arachne
mkdir /data2/suguru/temp/Polites_themistocles
mkdir /data2/suguru/temp/Limochores_sonora
mkdir /data2/suguru/temp/Chlosyne_palla
mkdir /data2/suguru/temp/Oarisma_garita
mkdir /data2/suguru/temp/Lycaena_nivalis
mkdir /data2/suguru/temp/Phyciodes_mylitta
mkdir /data2/suguru/temp/Hemiargus_ceraunus
mkdir /data2/suguru/temp/Colias_christina
mkdir /data2/suguru/temp/Erynnis_tristis
mkdir /data2/suguru/temp/Hylephila_phyleus
mkdir /data2/suguru/temp/Lycaena_dorcas
mkdir /data2/suguru/temp/Thymelicus_lineola
mkdir /data2/suguru/temp/Pyrgus_ruralis
mkdir /data2/suguru/temp/Speyeria_mormonia
mkdir /data2/suguru/temp/Phoebis_sennae
mkdir /data2/suguru/temp/Abaeis_nicippe
mkdir /data2/suguru/temp/Battus_philenor
mkdir /data2/suguru/temp/Speyeria_zerene
mkdir /data2/suguru/temp/Chlosyne_californica
mkdir /data2/suguru/temp/Brephidium_exilis
mkdir /data2/suguru/temp/Piruna_pirus
mkdir /data2/suguru/temp/Phyciodes_tharos
mkdir /data2/suguru/temp/Ochlodes_yuma
mkdir /data2/suguru/temp/Icaricia_lupini
mkdir /data2/suguru/temp/Asterocampa_celtis
mkdir /data2/suguru/temp/Icaricia_shasta
mkdir /data2/suguru/temp/Leptotes_marina
mkdir /data2/suguru/temp/Hamadryas_februa
mkdir /data2/suguru/temp/Glaucopsyche_piasus
mkdir /data2/suguru/temp/Satyrium_saepium
mkdir /data2/suguru/temp/Euptoieta_claudia
mkdir /data2/suguru/temp/Phyciodes_phaon
mkdir /data2/suguru/temp/Echinargus_isola
mkdir /data2/suguru/temp/Erynnis_icelus
mkdir /data2/suguru/temp/Nymphalis_l-album
mkdir /data2/suguru/temp/Speyeria_hydaspe
mkdir /data2/suguru/temp/Vanessa_annabella
mkdir /data2/suguru/temp/Libytheana_carinenta
mkdir /data2/suguru/temp/Speyeria_hesperis
mkdir /data2/suguru/temp/Euphydryas_editha
